name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - v0.3.0-alpha
        - v0.2.0-alpha
        - v0.1.0-alpha
      default: 0
    validations:
      required: true
  - type: textarea
    id: recreate-steps
    attributes:
      label: Steps to recreate issue
      description: Please give the steps that were taken to cause this bug; so that we can help fix it more quickly!
      render: shell
      placeholder: Step 1) ...
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
