# This is a basic workflow that is manually triggered

name: Build Executable

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version Number'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / macos-latest>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: "fjord.py"
          requirements: 'requirements.txt'
          upload_exe_with_name: 'fjord.exe'
          options: --onefile, --name "Fjord", --windowed, 
